### ISSUE TITLE
Re-calibrate hard limits of exoskeleton

### ISSUE THREAD

**Issue by martijnvandermarel** [project-march/hardware-interface#146]
Sometimes the exoskeleton indicates it is outside its hard limits. Since this is not possible, the hard limits in the yaml are probably not exactly corresponding with the real hard limits. 
Recalibration would fix this. (Reading joint values and adapting yaml based on real hard limits, then re-calculating zero position if necessary)

**Comment by Roelemans** [comment]
Moved to Jira
