### ISSUE TITLE
Refactor settings to use constants instead of memory adresses

### ISSUE THREAD

**Issue by Ishadijcks** [project-march/hardware-interface#30]
Create a header file with constants with something like this:

```
MODE_OF_OPERATION_ADDRESS = 0x1234
```

And refactor these statements with the consts.

```
success &= sdo_bit8(slaveIndex, 0x6060, 0, 8);
```

**Comment by Ishadijcks** [comment]
@martijnvandermarel I'm a bit conflicted on how to implement this cleanly. It would make sense to add them as IMCObjects, but that would be odd in the PDOmapping, thoughts?

**Comment by martijnvandermarel** [comment]
We could make a seperate IMC addresses constants file, and refactor PDOmapping with these constants as well, alongside the sdo writing instances

**Comment by Ishadijcks** [comment]
Hmm that would require you to add a new PDOobject in 3 places, that's kind of overkill. Will probably need to refactor the IMCObject enum to include the address.

**Comment by Roelemans** [comment]
Seems to be finished to some extend; will not look into it untill we discover the problem ourselves.
