### ISSUE TITLE
check for presence of slaves every ethercat cycle

### ISSUE THREAD

**Issue by martijnvandermarel** [project-march/hardware-interface#31]
be able to detect if slaves are lost and notify developer if slave is permanently lost. If temporarily lost, try to re-establish connection?

**Comment by Ishadijcks** [comment]
Can we actively re-establish the connection or is it mostly hoping it works again?
I'm not sure of the frequency of this happening but isn't this definitely a fatal exception?

How does an IMC react if it no longer gets commands? Default to 0 or repeat the last command?

**Comment by Ishadijcks** [comment]
Implemented in #61
