### ISSUE TITLE
Add current limit to IMotionCube.cpp 

### ISSUE THREAD

**Issue by JitskedeVries** [project-march/hardware-interface#38]
The CurrentLimit is defined in the PDO mapping, but the value is nowhere set. 
The current limit [IU] is dependent on the current_limit[A] and the Ipeak[A] and is calculated with a formula defined in the IMC bible. The calculated value can be found here: https://confluence.projectmarch.nl:8443/display/41TECH/Safety+Joint+States+Limits

**Comment by Roelemans** [comment]
Seems to have been implemented already.
