### ISSUE TITLE
Make sure every EtherCAT cycle has constant time

### ISSUE THREAD

**Issue by martijnvandermarel** [project-march/hardware-interface#56]
The amount of time that needs to be slept every ethercat cycle should ideally be adapted based on how long the first part of the ethercat infinite loop takes. This will ensure every ethercat cycle is exactly x microseconds instead of x + time it takes to read/write ethercat buffers + time it takes to monitor slave connections etc.
This can probably be done with the standard chrono boost library in cpp? Time how long the first part of the loop takes (e.g. y microseconds) and then sleep for x-y microseconds. The total loop will then take x microseconds, as desired.

**Comment by Ishadijcks** [comment]
We could also use `Ros::Rate()` for this, not sure what's better
